
// lib/main.dart
//
// WHY Firebase.initializeApp() must be here:
// ─────────────────────────────────────────
// Firebase needs to connect to Google's servers before your app
// does anything. initializeApp() reads firebase_options.dart
// (the file flutterfire configure generates) and opens that
// connection. If you skip it, every Firebase call crashes.
//
// WHY it's async + await:
// ───────────────────────
// The connection takes a moment. "await" pauses here until it's
// done, so by the time runApp() fires, Firebase is fully ready.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // ← generated by: flutterfire configure
import 'providers/app_provider.dart';
import 'app.dart';

import 'package:flutter_dotenv/flutter_dotenv.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await dotenv.load(fileName: ".env");

  // ── FIREBASE INIT ──────────────────────────────────────────────
  // This is the ONE place you initialise Firebase for the whole app.
  // DefaultFirebaseOptions.currentPlatform picks the right config
  // for Android vs iOS automatically from firebase_options.dart.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // If you haven't run `flutterfire configure` yet, this will
    // throw. The app still launches so you can see the UI.
    debugPrint('Firebase init failed: $e');
    debugPrint('→ Run: flutterfire configure --project=YOUR_PROJECT_ID');
  }

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => UserProfileProvider()),
        ChangeNotifierProvider(create: (_) => HabitsProvider()),
        ChangeNotifierProvider(create: (_) => MedicationsProvider()),
        ChangeNotifierProvider(create: (_) => CheckupsProvider()),
        ChangeNotifierProvider(create: (_) => LifestyleProvider()),
        ChangeNotifierProvider(create: (_) => ChatProvider()),
        ChangeNotifierProvider(create: (_) => AccessibilityProvider()),
      ],
      child: const GreenBasketApp(),
    ),
  );
}